# Generated by Django 4.2.2 on 2023-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoan',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('catagory', models.CharField(max_length=50)),
                ('repayment', models.IntegerField()),
                ('collateral', models.CharField(max_length=200)),
                ('loan_term', models.CharField(max_length=200)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('maker', models.CharField(max_length=200)),
                ('authorizer', models.CharField(max_length=200)),
                ('interest', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSaving',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('defect', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('compulsary', models.IntegerField()),
                ('voluntary', models.IntegerField()),
                ('vocher', models.CharField(max_length=200)),
                ('maker', models.CharField(max_length=200)),
                ('authorizer', models.CharField(max_length=200)),
                ('total', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
