# Generated by Django 4.2.2 on 2023-07-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mekenet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersaving',
            old_name='defect',
            new_name='undue',
        ),
    ]
