# Generated by Django 4.2.2 on 2023-07-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_useranme_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
